### ISSUE TITLE
Perpetually says "loading..."

### ISSUE THREAD

**Issue by dreeves** [narthur/autodial#9]
## Replicata

1. Go to autodial.taskratchet.com as a new user
2. Click the button to authorize autodialer to access my beeswax
3. End up back on autodial.taskratchet.com

## Expectata

No more button to authorize, maybe some indication that I'm already authorized.

## Resultata

![image](https://user-images.githubusercontent.com/9928/146655711-cccdb645-a707-4392-9e2c-0f67a2028c52.png)

This persists even after page reload.

**Comment by narthur** [comment]
Hmm, that's definitely not supposed to happen. Can you check in Chrome console for error messages?

**Comment by narthur** [comment]
Also do you end up with your username and access token in the URL bar like you'd expect?

**Comment by dreeves** [comment]
![image](https://user-images.githubusercontent.com/9928/146655893-d1d544e9-df56-45b1-8be6-a5abb2146cb8.png)

**Comment by narthur** [comment]
Hmm, from your screenshot it looks like the Beeminder API responded with a 404... 🤔

**Comment by narthur** [comment]
I tried disabling and re-enabling for my account and it's still working fine. Are you able to refresh and try again? Do you still get the same errors?

**Comment by dreeves** [comment]
I just visited autodial.taskratchet.com again, saw the "ENABLE AUTODIALER" button, clicked it, and it immediately changed to "loading..." and stays that way even after a hard reload of the page.

**Comment by narthur** [comment]
@dreeves I've deployed a fix that should resolve your issue. Can you test and see when you get a chance?
